name: Deploy to kubernetes
on:
  push:
    branches:
      - "main"

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  TF_STATE_BUCKET_NAME: ${{ secrets.GCP_TF_STATE_BUCKET }}
  GAR_LOCATION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      
    - name: Docker configuration
      run: |-
        echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev
    
    - name: Build and push docker image
      run: |    ## Cambiar el nombre de la aplicacion "nodeapp"
        docker build -t us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/pythonappimage:$IMAGE_TAG .  
        docker push us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/pythonappimage:$IMAGE_TAG
      working-directory: ./pythonapp   ## Fijarme en el directorio donde esta la aplicacion

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform init
      run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="prefix=test"
      working-directory: ./Terraform

    - name: Terraform Plan
      run: |  ## Cambiar el nombre de la aplicacion "nodeapp"
        terraform plan \
        -var="region=us-central1" \
        -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
        -var="container_image=us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/pythonappimage:$IMAGE_TAG" \  
        -out=PLAN
      working-directory: ./Terraform

    - name: Terraform Apply
      run: terraform apply PLAN
      working-directory: ./Terraform
